server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080  servlet:    encoding:      charset: UTF-8      enabled: true      force: true

spring:
  mvc:
    view:
      # jsp 설정
      prefix: /WEB-INF/view/
      suffix: .jsp
  # 자동 새로고침
  devtools:
    livereload:
      enabled: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
##    hibernate.ddl-auto: create-drop # 이거 해놓으면 서버 시작시 데이터 입력 안됨.
#    hibernate.ddl-auto: none
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate.show_sql: true
#      hibernate.format_sql: true
#  datasource:
#    #url: jdbc:h2:mem:testdb
#    #url: jdbc:h2:file:~/Sources/tmp/testdb;AUTO_SERVER=TRUE
#    url: jdbc:h2:tcp://localhost/~/testdb;AUTO_SERVER=TRUE
#    #url: jdbc:h2:tcp://localhost/~/testdb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver